/*
 * tapi-topology API
 * tapi-topology API generated from tapi-topology.yang
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package es.tid.topologyModuleBase.TAPITopoModel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * Identifies the validation mechanism and describes the characteristics of that mechanism
 */
@ApiModel(description = "Identifies the validation mechanism and describes the characteristics of that mechanism")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-03-31T10:56:12.255Z")
public class ValidationMechanism   {
  @JsonProperty("validation-mechanism")
  private String validationMechanism = null;

  @JsonProperty("validation-robustness")
  private String validationRobustness = null;

  @JsonProperty("layer-protocol-adjacency-validated")
  private String layerProtocolAdjacencyValidated = null;

  public ValidationMechanism validationMechanism(String validationMechanism) {
    this.validationMechanism = validationMechanism;
    return this;
  }

   /**
   * Name of mechanism used to validate adjacency
   * @return validationMechanism
  **/
  @JsonProperty("validation-mechanism")
  @ApiModelProperty(value = "Name of mechanism used to validate adjacency")
  public String getValidationMechanism() {
    return validationMechanism;
  }

  public void setValidationMechanism(String validationMechanism) {
    this.validationMechanism = validationMechanism;
  }

  public ValidationMechanism validationRobustness(String validationRobustness) {
    this.validationRobustness = validationRobustness;
    return this;
  }

   /**
   * Quality of validation (i.e. how likely is the stated validation to be invalid)
   * @return validationRobustness
  **/
  @JsonProperty("validation-robustness")
  @ApiModelProperty(value = "Quality of validation (i.e. how likely is the stated validation to be invalid)")
  public String getValidationRobustness() {
    return validationRobustness;
  }

  public void setValidationRobustness(String validationRobustness) {
    this.validationRobustness = validationRobustness;
  }

  public ValidationMechanism layerProtocolAdjacencyValidated(String layerProtocolAdjacencyValidated) {
    this.layerProtocolAdjacencyValidated = layerProtocolAdjacencyValidated;
    return this;
  }

   /**
   * State of validatiion
   * @return layerProtocolAdjacencyValidated
  **/
  @JsonProperty("layer-protocol-adjacency-validated")
  @ApiModelProperty(value = "State of validatiion")
  public String getLayerProtocolAdjacencyValidated() {
    return layerProtocolAdjacencyValidated;
  }

  public void setLayerProtocolAdjacencyValidated(String layerProtocolAdjacencyValidated) {
    this.layerProtocolAdjacencyValidated = layerProtocolAdjacencyValidated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidationMechanism validationMechanism = (ValidationMechanism) o;
    return Objects.equals(this.validationMechanism, validationMechanism.validationMechanism) &&
        Objects.equals(this.validationRobustness, validationMechanism.validationRobustness) &&
        Objects.equals(this.layerProtocolAdjacencyValidated, validationMechanism.layerProtocolAdjacencyValidated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(validationMechanism, validationRobustness, layerProtocolAdjacencyValidated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidationMechanism {\n");
    
    sb.append("    validationMechanism: ").append(toIndentedString(validationMechanism)).append("\n");
    sb.append("    validationRobustness: ").append(toIndentedString(validationRobustness)).append("\n");
    sb.append("    layerProtocolAdjacencyValidated: ").append(toIndentedString(layerProtocolAdjacencyValidated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

